name: Preview

on:
  pull_request_target:
    types: [opened, reopened, synchronize]

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      deployments: write
    environment: Preview
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          ref: ${{ github.event.pull_request.head.sha }}
          fetch-depth: 0

      - name: Setup Node.JS
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'yarn'

      - name: Install Node Packages
        run: yarn

      - name: Adhoc solution for package sharp
        run: yarn add sharp --ignore-engines

      - name: Genereate static website files
        run: yarn build

      - name: Deploy to Cloudflare Pages Preview
        uses: cloudflare/pages-action@v1.5.0
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: e40ca42475e880f2bb8fef31bc321e4c
          projectName: blog-krishu-moe
          directory: dist
          gitHubToken: ${{ secrets.GITHUB_TOKEN }}
          branch: pr-${{ github.event.pull_request.id }}